### ISSUE TITLE
Job Processor not showing Autodesk.BOMReport

### ISSUE THREAD

**Issue by olejens3003** [koechlm/Vault-Sample---Item-BOM-Report-Job#1]
Hi Markus
Can you please explain more how to get this up and running. I did everything you mentioned and dumped the files into VAULT 2019 Extension but nothing is showing up in the job processor. Would be nice if you can help to get this up and running as I require urgently for SAP to get the BOM report automatically pushed into a certain folder from VAULT. Can you make this code work as well under VAULT 2020? 
I did send you a message with LinkedIN (auf Deutsch) 
Danke und Gruss
Jens

**Comment by olejens3003** [comment]
Got it up and running now but only job processor - creating the excel and push to VAULT folder as well c: drive is not working. I am using VAULT 2019.3 - is this the issue? Did all settings as you mentioned.

**Comment by koechlm** [comment]
> Hi Markus
> Can you please explain more how to get this up and running. I did everything you mentioned and dumped the files into VAULT 2019 Extension but nothing is showing up in the job processor. Would be nice if you can help to get this up and running as I require urgently for SAP to get the BOM report automatically pushed into a certain folder from VAULT. Can you make this code work as well under VAULT 2020?
> I did send you a message with LinkedIN (auf Deutsch)
> Danke und Gruss
> Jens

I am going to share the 2020 branch (source) and binaries asap.

**Comment by koechlm** [comment]
In regards to the issue that you are facing in 2019.3, it is hard to support, if you don't share any details, like an error in Job Queue or screenshots that verify that the job is registered and available properly in the Job Processor.

**Comment by olejens3003** [comment]
Hi Markus, thanks for answering. I am getting no errors and everything looks like okay. I can see Autodesk,BOMReport in the job processor job types and job queue  is pushing to job processor exactly as you showed in your video. When going to the folders I can see nothing, not local nor VAULT. 

Setting file is:
<?xml version="1.0" encoding="utf-8" ?>
<settings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  
  
  <bomType>MULTI_LEVEL</bomType>
  
  
  <reportTemplate>BOM - Multi-Level.rdlc</reportTemplate>

  
  
  <reportsVaultPath>$/SAP_BOM</reportsVaultPath>

  
  <attachUpdateReport>true</attachUpdateReport>

  
  
  <ReportOutFormat>XLSX</ReportOutFormat>
  
  
  
  <ReportOutExtLocation>C:\SAP_BOM\</ReportOutExtLocation>
  
  
  
  <quickChangeState>Quick-Change</quickChangeState>
  
  
  <generatePartReports>false</generatePartReports>
  
</settings>

Currently I am not in the office but I can send you screenshots showing that job processor is working and pushing Sunday. . Can I send you any log file?

**Comment by koechlm** [comment]
Sounds like an ACL problem for the job user logged in to Job Processor. There is no logging for this sample job, as it should handle all known hurdles. Let me check that ACL is also covered in the 2020 update.

**Comment by koechlm** [comment]
I checked the handling for ACL on item lifecycle transitions (required to attach) and also on item edits. Both are handled and would report back as an error to the job queue.

**Comment by olejens3003** [comment]
i am admin and have all rights - same was used for the job processor. no error was reported and the job was gone after execution in job queue and processor. i followed on both and checked it. let me try 2020 sunday and i will upload some screen shots from 2019.3. did i need to take care of anything else inside vault, beside what you mentioned already?

**Comment by koechlm** [comment]
To investigate I suggest doing all steps manually by the same user the job will use.
1) Change state of the item -> Quick Change (or the state you configured)
2) Create BOM report consuming the template used by the job
3) Upload the file to the target location in Vault
4) Attach the file to the item
5) Release the item
Then investigate the job. Does the job run at all? - it won't if the downloaded archive file has a security block on it. Remove it before you extract the binaries. Is the output file created locally?

**Comment by koechlm** [comment]
2020 version is published as promised this morning.

**Comment by olejens3003** [comment]
Hi Markus

I did now what you suggested but still it is not creating nor pushing the BOM Excel file. Here some pictures. I created and added the BOM report manually as you said as well added to the assembly document. The job processor is doing the job afterwards but nothing happened and I do not receive any error. 

![JobQ](https://user-images.githubusercontent.com/55532412/65383968-70f6cc80-dd2d-11e9-981e-851d60238b6b.PNG)

![BOM](https://user-images.githubusercontent.com/55532412/65383973-76541700-dd2d-11e9-8567-17f8e3458d0f.PNG)

![BOM1](https://user-images.githubusercontent.com/55532412/65383977-7bb16180-dd2d-11e9-8ade-69df6ec2803c.PNG)

I created the folder on$/ as well on network folder. 

When try to do get I receive the following message:
![NetWork](https://user-images.githubusercontent.com/55532412/65384008-f1b5c880-dd2d-11e9-9f75-cb95a27e69ec.PNG)

I need to say that the Item Master is pushed by a software called Woodworks for Inventor and after this point we are doing nothing in VAULT. This issue with get is only on Item Master not on Project Folder. 

Thanks
Jens

**Comment by olejens3003** [comment]
I checked again and looks like I have some issues here with the file itself and can't get the file from Project either. Will keep you posted.

**Comment by olejens3003** [comment]
I fixed the issue with the network path now as well put the local folder and VAULT folder into the specified location ipj. Created the report manually and added to the item and into the VAULT folder - changed the state and job processor was running without error. Still nothing. It is not creating the report. Please let me know if I can send anything else to show you what I am doing and to find out what I am doing wrong. Did I need to setup the lifecycle with your tool or the tool from VAULT? I did this now with the tool from VAULT - can this be the issue? (did send you a message this morning to this tool as I am getting an error)

**Comment by koechlm** [comment]
To speed up investigation I suggest remotely looking on your machine. Which time-zone are you in?

**Comment by olejens3003** [comment]
I am Dubai - 2 hours from you. 
Can you please contact anup.rajan[@]fdc-interiors.com and he can organize everything to connect to one of our workstations to investigate the issue. 

Thanks
Jens

**Comment by olejens3003** [comment]
Hi Markus - did you send him an email? I really like to sort this out and organize the remote session. 
Thanks

**Comment by koechlm** [comment]
No, sorry I didn't - too many task concurrently :(. Will send Zoom meeting invite here in a minute.

**Comment by koechlm** [comment]
Does 11:30 CEST fit (35min from now)?. The remote meeting: https://autodesk.zoom.us/j/592762214

**Comment by olejens3003** [comment]
Sure and thanks - I did send your information to our IT and they will take care.

**Comment by koechlm** [comment]
Done.
