### ISSUE TITLE
Excel XML based file is not being generated

### ISSUE THREAD

**Issue by r9guy** [koechlm/Vault-Sample---Item-BOM-Report-Job#2]
then running the extension the rendered report is not being generated if the chosen format is XLSX.
PDF and XLS are working fine. perhaps[ this is](https://social.msdn.microsoft.com/Forums/en-US/4515d853-216f-4896-a170-f431a004e786/render-to-xlsx-format-for-localreport-using-microsoft-reportviewer-dll-version-110336616?forum=vsreportcontrols) the issue

**Comment by koechlm** [comment]
Sure, report viewer version 12.0.0.0 is expected. I am going to include it to solve this dependency.

**Comment by koechlm** [comment]
Would you mind validating the attached debug version, please?
[Autodesk.BOMReportJobSample_DebugVersionReportViewer.zip](https://github.com/koechlm/Vault-Sample---Item-BOM-Report-Job/files/3651682/Autodesk.BOMReportJobSample_DebugVersionReportViewer.zip)

**Comment by r9guy** [comment]
will do it on Sunday.
