### ISSUE TITLE
Compatibility with VAULT CLIENT 2024 and get it up and running

### ISSUE THREAD

**Issue by RevanthNS** [koechlm/Vault-Sample---Item-BOM-Report-Job#8]
Hi i am new to VAULT, we are working with AutoCAD mechanical drawings , can it be used to get the BOM of ITEMS in item master from VAULT CLIENT 2024 or 2025 so that it can be imported to AutoCAD Mechanical drawing BOM.

**Comment by koechlm** [comment]
Sure, you could grab the report result excel file and import this into your drawing. However, AutoCAD Mechanical has comprehensive BOM capabilities that are linked with Vault Items as a default. So why would you import a BOM from Vault into a drawing (dis-connected) while you have an associative option? If you don't leverage AutoCAD mechanical BOM, then ... yes.

**Comment by koechlm** [comment]
Answered. No issue, rather than discussion.

**Comment by RevanthNS** [comment]
I tried the job processor but it is not executing the status is pending.
